version: "3.9"

services:
  service:
    container_name: ${CONTAINER_NAME}
    image: ${DOCKER_REPOSITORY}:latest
    hostname: stg.moneystats.angular
    ports:
      - "10000:80"

    networks:
      docker-network:
        aliases:
          - stg.moneystats.angular

networks:
  docker-network:
    external: true
